### PR TITLE
Added a config file

### PR DESCRIPTION
**Pull request by namzop**
#45 added a config file

### CODE REVIEW

**Comment by devilAPI** [comment]
uhm. i literally said that i was done making a config file so noone else does it for no reason.

Well, you made a better implementation of that feature. I would recommend @cryptofyre to use this one

**Comment by devilAPI** [comment]
> Im currently working on this, will submit PR in a week

**Comment by devilAPI** [comment]
this does not work, its just a window without even a titlebar

**Comment by devilAPI** [comment]
idk

**Comment by namzop** [comment]
yea bro that was due to a typo. i fixed it!

it's working now

**Comment by namzop** [comment]
yea bro that was due to a typo. i fixed it.

image

**Comment by devilAPI** [comment]
perfect its fixed!

**Comment by cryptofyre** [comment]
Merged!

**Pull request merged**
