### PR TITLE
core, your bad

### PR DESCRIPTION
**Pull request by brandonplank**
get good

### CODE REVIEW

**Comment by cryptofyre** [comment]
commit shit dead

**Comment by coredev-uk** [comment]
no ty

**Comment by brandonplank** [comment]
yes ty

**Comment by coredev-uk** [comment]
tbf i didnt do that originally

**Comment by cryptofyre** [comment]
cap

**Comment by coredev-uk** [comment]
https://github.com/cryptofyre/Apple-Music-Electron/commit/2698343465b3c7fcf5fecd25422c11fda67845bb

**Comment by coredev-uk** [comment]
not cap

**Comment by coredev-uk** [comment]
i just cleaned it up because it looks weird

**Comment by cryptofyre** [comment]
sussy baka <3

**Comment by brandonplank** [comment]
core your bad at markdown, im bad a javascript. its ok to suck.

**Comment by cryptofyre** [comment]
you suck more

**Comment by brandonplank** [comment]
i've programmed more than you have

**Comment by cryptofyre** [comment]
bullshit

**Comment by brandonplank** [comment]
sussy baka balls

**Comment by cryptofyre** [comment]
mf ill ban you from the repo watch me

**Comment by brandonplank** [comment]
pls no

**Comment by cryptofyre** [comment]
*pulls out the 9*

**Comment by brandonplank** [comment]
*** pulls out my 85 repos ***

**Comment by cryptofyre** [comment]
you mean 1 actual repo

**Comment by brandonplank** [comment]
https://github.com/brandonplank/flappybird
https://github.com/brandonplank/plank-tools
https://github.com/brandonplank/pico-ambient-project
https://github.com/brandonplank/PlankFilza
https://github.com/brandonplank/Arduino-Pico
https://github.com/brandonplank/iPAPatcher
https://github.com/brandonplank/ImposterConfig
https://github.com/brandonplank/Haptic13
https://github.com/brandonplank/Mobile-Cracker
https://github.com/brandonplank/Plankton-Debugger
https://github.com/brandonplank/kuzz
https://github.com/brandonplank/tihmstarInstaller
https://github.com/brandonplank/rootlessJB4

**Comment by brandonplank** [comment]
Me: 694 stars total
You: 246 stars total
Core: 2 stars

**Comment by brandonplank** [comment]
poor core

**Comment by child-duckling** [comment]
👀

**Comment by cryptofyre** [comment]
no please

**Comment by child-duckling** [comment]
Me with my singular star: 👁👅👁

**Pull request merged**
