### PR TITLE
Various changes (see below)

### PR DESCRIPTION
**Pull request by coredev-uk**
- Fixed how site detection works as before it didn't check correctly and it would always return false.
- Added a close button minimize option, where users can set it so the window is minimized instead of the entire app being quit.
- Added a new tray icon context menu method where if the window is not hidden then it lets you minimize it and if it is hidden then it lets you maximise or show it.
- No longer need to change the frame variable if you use customtitlebar
- No longer need to uncomment lines if you'd like to use glasstron.

### CODE REVIEW

**Comment by cryptofyre** [comment]
This is great! Thanks for the PR, I should be able to merge this soon once I process the others.

**Comment by coredev-uk** [comment]
Thanks, I've been wanting to make a PR for this for a while. I also created a theme system in my [dev](https://github.com/coredev-uk/Apple-Music-Electron/tree/dev) branch which I could make a pr for if you'd like, it's not that easy if you'd want to create your own custom theme but I managed to bring it down to only about 5 variables to theme the UI.

**Comment by cryptofyre** [comment]
That sounds great! I'd love to see a PR for that.

**Comment by devilAPI** [comment]
> Fixed how site detection works as before it didn't check correctly and it would always return false.

😑😑😑

**Comment by devilAPI** [comment]
> Thanks, I've been wanting to make a PR for this for a while. I also created a theme system in my [dev](https://github.com/coredev-uk/Apple-Music-Electron/tree/dev) branch which I could make a pr for if you'd like, it's not that easy if you'd want to create your own custom theme but I managed to bring it down to only about 5 variables to theme the UI.

I would love to see that :)

**Comment by coredev-uk** [comment]
Please could you not process this PR there is something wrong with it that I need to fix, didn't notice that this was the issue until now.

**Comment by cryptofyre** [comment]
Sure, I don't move into my apartment till 3PM Central. So take all the time you need and feel free to delay.

**Comment by cryptofyre** [comment]
Is this ready to be merged?

**Comment by coredev-uk** [comment]
I've merged #58 into this pr, I am very unsure about the whole thing. I keep getting given errors for the upsell, logo and custom titlebar and they keep bugging out in the window, this might just be an issue with me, but I haven't touched that part of the code, nor has it been affected by any PR made lately. You can merge this if you'd like but I'm just not sure.

**Comment by coredev-uk** [comment]
This is ready to be merged now.

**Review by cryptofyre — APPROVED** [review]

**Pull request merged**
